---
abstract: "A readonly variant of 'my' called 'val'"
author:
  - 'Chuck Adams <cja987@gmail.com>'
build_requires:
  Module::Build::Tiny: 0.025
configure_requires:
  Module::Build::Tiny: 0.025
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Syntax-Keyword-Val
requires:
  Data::Lock: 0
  Keyword::Simple: 0
version: 0.002
